name: Upload and ingest Edible species list into ALA Lists

on:
  workflow_dispatch:

jobs:
  graphql-replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Init Node project
        run: npm init -y

      - name: Install dependencies
        run: npm install axios form-data

      - name: Upload and ingest species list
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          LIST_ID: "681363e168ab293a5a947908"
          LIST_PREFIX: "ARGA_Data_Imports_Edible_List_MASTER_"
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const axios = require('axios');
          const FormData = require('form-data');

          const listId = process.env.LIST_ID;
          const token = process.env.ACCESS_TOKEN;
          const prefix = process.env.LIST_PREFIX;
          const fileDir = './imported_GoogleSheets/Edible_species_list';

          const fileMatch = fs.readdirSync(fileDir)
            .filter(f => f.startsWith(prefix) && f.endsWith('.csv'))
            .map(f => ({
              name: f,
              time: fs.statSync(path.join(fileDir, f)).mtime.getTime()
            }))
            .sort((a, b) => b.time - a.time)[0];

          if (!fileMatch) {
            console.error("❌ No matching file found.");
            process.exit(1);
          }

          const filePath = path.join(fileDir, fileMatch.name);
          console.log(`📄 Using file: ${fileMatch.name}`);

          const form = new FormData();
          form.append('file', fs.createReadStream(filePath));

          console.log("📤 Uploading file...");
          axios.post(`https://lists-ws.test.ala.org.au/upload`, form, {
            headers: {
              ...form.getHeaders(),
              Authorization: `Bearer ${token}`
            }
          })
          .then(response => {
            const localFile = response.data.localFile;
            if (!localFile) {
              console.error("❌ Upload failed: no file handle was returned");
              process.exit(1);
            }
            console.log(`✅ Uploaded. Local file ID: ${localFile}`);
            console.log("🚀 Triggering reingest...");

            return axios.post(
              `https://lists-ws.test.ala.org.au/ingest/${listId}`,
              new URLSearchParams({ file: localFile }),
              {
                headers: {
                  'Content-Type': 'application/x-www-form-urlencoded',
                  Authorization: `Bearer ${token}`
                }
              }
            );
          })
          .then(() => {
            console.log("✅ Ingest triggered successfully.");
          })
          .catch(err => {
            console.error("❌ Error:", err.response ? err.response.data : err.message);
            process.exit(1);
          });
          EOF
