name: Update Species List License (REST)

on:
  workflow_dispatch:
    inputs:
      speciesListID:
        description: 'ID of the species list to update'
        required: true
        default: '67b51f358a0f582bd7ef9d73'
      licenseURL:
        description: 'New license URL'
        required: true
        default: 'https://creativecommons.org/licenses/by/4.0/'

jobs:
  update-license:
    runs-on: ubuntu-latest
    steps:
      - name: Init Node project
        run: npm init -y

      - name: Install axios
        run: npm install axios

      - name: Send REST PUT to update license
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          LIST_ID: ${{ github.event.inputs.speciesListID }}
          LICENSE: ${{ github.event.inputs.licenseURL }}
        run: |
          node <<'EOF'
          const axios = require('axios');

          const token = process.env.ACCESS_TOKEN;
          const listId = process.env.LIST_ID;
          const license = process.env.LICENSE;

          const url = `https://lists-ws.test.ala.org.au/speciesList/${listId}`;
          const payload = {
            license: license
          };

          const headers = {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
          };

          (async () => {
            try {
              const res = await axios.put(url, payload, { headers });
              console.log("✅ License updated:", res.data);
            } catch (err) {
              console.error("❌ REST error:", err.response?.data || err.message);
              process.exit(1);
            }
          })();
          EOF
